title: Matthew Miner
description: Software + Media Developer
baseurl: "" # Subpath, e.g. /blog/
url: "http://matthewminer.com" # Base hostname and protocol

# Build settings
compress_html:
  clippings: all
  comments: ["/*! ", " */"]
redcarpet:
  extensions: ["smart"]
sass:
  style: compressed
