title: Matthew Miner
description: Software + Media Developer
baseurl: "" # Subpath, e.g. /blog/
url: "http://matthewminer.com" # Base hostname and protocol

# Build settings
redcarpet:
  extensions: ["smart"]
sass:
  style: compressed
